debug: true
spring:
  cloud:
    stream:
      bindings:
        sqrt-in-0:
          destination: numbers
        sqrt-out-0:
          destination: sqrt-numbers
        log-in-0:
          destination: sqrt-numbers
      kafka:
        streams:
          binder:
            functions:
              sqrt:
                application-id: sqrtApplicationId
              log:
                application-id: logApplicationId
    function:
      definition: sqrt;log
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
      isolation-level: read_committed
